server:
    port: 8000
    context-path: /

spring:
    datasource:
        platform: h2
        username: sa
        password:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:payment
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: create
    jackson:
        property-naming-strategy: SNAKE_CASE
        default-property-inclusion: NON_NULL


logging:
    level:
        - org:
            springframework: INFO